### ISSUE TITLE
KeyError: 'pool_op_kernel_sizes' in nnUNetPreTrainer_PED.py

### ISSUE THREAD

**Issue by eclouder** [WltyBY/LNQ2023_training_code#3]
Hi WityBY:
    I encountered a KeyError: 'pool_op_kernel_sizes' error when running nnUNetv2_train. Below is the detailed traceback:
Traceback (most recent call last):
  File "D:\Code\Python\DLforLNQ\nnUNet\nnunetv2\run\run_training.py", line 266, in <module>
    run_training_entry()
  File "D:\Code\Python\DLforLNQ\nnUNet\nnunetv2\run\run_training.py", line 259, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.d, args.p, args.pretrained_weights,
  File "D:\Code\Python\DLforLNQ\nnUNet\nnunetv2\run\run_training.py", line 200, in run_training
    nnunet_trainer.run_training()
  File "D:\CodeLauguage\Python\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetPreTrainer_PED.py", line 1203, in run_training
    self.on_train_start()
  File "D:\CodeLauguage\Python\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetPreTrainer_PED.py", line 798, in on_train_start
    self.dataloader_train, self.dataloader_val = self.get_dataloaders()
  File "D:\CodeLauguage\Python\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetPreTrainer_PED.py", line 572, in get_dataloaders
    deep_supervision_scales = self._get_deep_supervision_scales()
  File "D:\CodeLauguage\Python\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetPreTrainer_PED.py", line 297, in _get_deep_supervision_scales
    self.configuration_manager.pool_op_kernel_sizes), axis=0))[:-1]
  File "D:\CodeLauguage\Python\Lib\site-packages\nnunetv2\utilities\plans_handling\plans_handler.py", line 114, in pool_op_kernel_sizes
    return self.configuration['pool_op_kernel_sizes']
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'pool_op_kernel_sizes'
Steps to Reproduce:
nnUNetv2_train 80 3d_fullres all -tr=nnUNetPreTrainer_PED

**Comment by WltyBY** [comment]
I think this is because I did not use deep supervision in the whole task. However, during the code upload process, the uploaded code version may be wrong. I modified lines 572 and 573 in the nnUNetPreTrainer_PED code.
`# deep_supervision_scales = self._get_deep_supervision_scales()`
`deep_supervision_scales = None`
